### ISSUE TITLE
Mint Page Deployment

### ISSUE THREAD

**Issue by ConnectCoincade** [ConnectCoincade/bosscultr-website#3]
Build a Separate page for minting of our Bosses. The design must be having a desktop-first approach here.

## Dependencies:

- [ ] Design For Mobile, Desktop & Tab Version.

## Tasks:

- [x] #4
- [x] #5
- [x] #6
- [x] #8
- [x] #7

**Comment by yashcoincade** [comment]
Scheduled for Later
